SHELL := /usr/bin/env bash
.DEFAULT_GOAL := help

DC      := docker compose
APP_URL ?= http://localhost:8484

# ─── Help ─────────────────────────────────────────────────────────────────

.PHONY: help
help: ## Show this help
	@awk 'BEGIN { FS = ":.*##"; print "Atlas targets:\n" } \
		/^[a-zA-Z0-9_.-]+:.*##/ { printf "  \033[36m%-22s\033[0m %s\n", $$1, $$2 }' $(MAKEFILE_LIST)
	@echo
	@echo "Common flows:"
	@echo "  1. make up                   # app + caddy only, no data"
	@echo "  2. make geocoding            # + Photon, Placeholder (with WOF), libpostal"
	@echo "  3. make routing              # + Valhalla (downloads PBF + SRTM)"
	@echo "  4. make pois                 # + Overpass (long ingest)"
	@echo "  5. make full                 # everything except OTP (which needs manual GTFS)"
	@echo "  6. make status / logs / down"

# ─── Lifecycle ────────────────────────────────────────────────────────────

.PHONY: up
up: env ## Start the bare stack (caddy + app)
	$(DC) up -d
	@echo "→ $(APP_URL)"

.PHONY: down
down: ## Stop everything (any profile); preserves data volumes
	$(DC) --profile all --profile data-setup down

.PHONY: restart
restart: ## Restart caddy + app to pick up a new image
	$(DC) pull app caddy
	$(DC) up -d caddy app

.PHONY: status
status: ## Show running services + health
	@$(DC) --profile all ps

.PHONY: logs
logs: ## Tail logs across all running services (Ctrl-C to exit)
	$(DC) logs -f --tail=50

.PHONY: env
env: ## Create .env from .env.example if missing
	@if [ ! -f .env ]; then \
		cp .env.example .env; \
		echo "Created .env — edit SECRET_KEY_BASE before booting in production"; \
	fi

# ─── Region presets ───────────────────────────────────────────────────────

REGIONS_DIR := regions

.PHONY: region
region: ## Switch to a region preset: make region NAME=berlin|germany|europe|planet|multi-dach|...
	@if [ -z "$(NAME)" ]; then \
		echo "Usage: make region NAME=<preset>"; \
		echo "Available presets:"; \
		ls -1 $(REGIONS_DIR)/*.env 2>/dev/null | sed 's|$(REGIONS_DIR)/||; s|\.env||' | awk '{print "  " $$0}'; \
		exit 1; \
	fi
	@if [ ! -f $(REGIONS_DIR)/$(NAME).env ]; then \
		echo "ERROR: no preset at $(REGIONS_DIR)/$(NAME).env"; \
		exit 1; \
	fi
	@$(MAKE) env
	@# Preserve SECRET_KEY_BASE if .env already set it
	@grep -q '^SECRET_KEY_BASE=' .env 2>/dev/null && grep '^SECRET_KEY_BASE=' .env > /tmp/.apo-secret || cp .env.example .env
	@# Replace region-related lines in .env
	@cp $(REGIONS_DIR)/$(NAME).env .env.new
	@if [ -f /tmp/.apo-secret ]; then cat /tmp/.apo-secret >> .env.new; fi
	@grep -E '^(DATABASE_URL|RAILS_)' .env >> .env.new 2>/dev/null || true
	@mv .env.new .env
	@rm -f /tmp/.apo-secret
	@if grep -q '^PBF_URLS=' .env; then \
		echo "Multi-region preset detected — run 'make merge-pbf' to produce the merged PBF before bootstrapping."; \
	fi
	@echo "Switched to region: $$(grep '^REGION_LABEL=' .env | cut -d= -f2-)"
	@echo "  PBF: $$(grep '^PBF_URL=' .env | cut -d= -f2-)"
	@echo "  Photon: $$(grep '^COUNTRY_CODE=' .env | cut -d= -f2-)"

.PHONY: region-list
region-list: ## List all region presets
	@echo "Available region presets:"
	@for f in $(REGIONS_DIR)/*.env; do \
		name=$$(basename $$f .env); \
		label=$$(grep '^REGION_LABEL=' $$f | cut -d= -f2- | tr -d '"'); \
		echo "  $$name — $$label"; \
	done

.PHONY: region-create-country
region-create-country: ## Create a country preset. NAME=france CODE=fr GEOFABRIK=europe/france. Optional LAT=, LON=, ZOOM=.
	@if [ -z "$(NAME)" ] || [ -z "$(CODE)" ] || [ -z "$(GEOFABRIK)" ]; then \
		echo "Usage: make region-create-country NAME=france CODE=fr GEOFABRIK=europe/france"; \
		echo "       (find paths at https://download.geofabrik.de/)"; \
		exit 1; \
	fi
	@dest=$(REGIONS_DIR)/$(NAME).env; \
	if [ -e "$$dest" ]; then echo "ERROR: $$dest already exists"; exit 1; fi; \
	{ \
		echo "# Auto-generated by 'make region-create-country'"; \
		echo "REGION_NAME=$(NAME)"; \
		echo "REGION_LABEL=\"$(NAME) (country)\""; \
		echo "COUNTRY_CODE=$(CODE)"; \
		echo "PBF_URL=https://download.geofabrik.de/$(GEOFABRIK)-latest.osm.pbf"; \
		echo "PBF_NAME=$$(basename $(GEOFABRIK))-latest.osm.pbf"; \
		echo "OVERPASS_DIFF_URL=https://download.geofabrik.de/$(GEOFABRIK)-updates/"; \
		echo "DEFAULT_LAT=$${LAT:-0}"; \
		echo "DEFAULT_LON=$${LON:-0}"; \
		echo "DEFAULT_ZOOM=$${ZOOM:-5}"; \
	} > $$dest; \
	echo "Created $$dest. Switch with: make region NAME=$(NAME)"

.PHONY: region-create-city
region-create-city: ## Create a city preset. NAME=tokyo BBBIKE=Tokyo COUNTRY=jp. Optional LAT=, LON=, ZOOM=.
	@if [ -z "$(NAME)" ] || [ -z "$(BBBIKE)" ] || [ -z "$(COUNTRY)" ]; then \
		echo "Usage: make region-create-city NAME=tokyo BBBIKE=Tokyo COUNTRY=jp"; \
		echo "       (find names at https://download.bbbike.org/osm/bbbike/)"; \
		exit 1; \
	fi
	@dest=$(REGIONS_DIR)/$(NAME).env; \
	if [ -e "$$dest" ]; then echo "ERROR: $$dest already exists"; exit 1; fi; \
	{ \
		echo "# Auto-generated by 'make region-create-city'"; \
		echo "REGION_NAME=$(NAME)"; \
		echo "REGION_LABEL=\"$(BBBIKE) (city)\""; \
		echo "COUNTRY_CODE=$(COUNTRY)"; \
		echo "PBF_URL=https://download.bbbike.org/osm/bbbike/$(BBBIKE)/$(BBBIKE).osm.pbf"; \
		echo "PBF_NAME=$(BBBIKE).osm.pbf"; \
		echo "OVERPASS_DIFF_URL="; \
		echo "DEFAULT_LAT=$${LAT:-0}"; \
		echo "DEFAULT_LON=$${LON:-0}"; \
		echo "DEFAULT_ZOOM=$${ZOOM:-11}"; \
	} > $$dest; \
	echo "Created $$dest. Switch with: make region NAME=$(NAME)"

.PHONY: merge-pbf
merge-pbf: ## Multi-region: download listed PBFs + merge via osmium → data/osm/<merged>.osm.pbf
	@if ! grep -q '^PBF_URLS=' .env; then \
		echo "Not a multi-region preset. PBF_URLS not set in .env."; \
		exit 1; \
	fi
	@mkdir -p data/osm
	@source .env && \
		set -e && \
		merged="data/osm/$$PBF_NAME" && \
		echo "Downloading $$(echo $$PBF_URLS | wc -w | tr -d ' ') PBFs..." && \
		sources="" && \
		for url in $$PBF_URLS; do \
			fname=$$(basename $$url); \
			if [ ! -f "data/osm/$$fname" ]; then \
				echo "  → $$fname"; \
				curl -fL --progress-bar -o "data/osm/$$fname" "$$url"; \
			else \
				echo "  ✓ $$fname (cached)"; \
			fi; \
			sources="$$sources data/osm/$$fname"; \
		done && \
		echo "Merging into $$merged via osmium-tool..." && \
		docker run --rm -v "$$(pwd)/data/osm:/data" -w /data stefda/osmium-tool osmium merge $$(echo $$sources | sed 's|data/osm/||g') -O -o $$PBF_NAME && \
		echo "Done: $$(du -sh $$merged | cut -f1)"

# ─── Data bootstrap ───────────────────────────────────────────────────────

.PHONY: geocoding
geocoding: env placeholder-data ## Boot geocoding stack (Photon + Placeholder + libpostal)
	$(DC) --profile geocoding up -d photon libpostal placeholder
	@echo "Photon is downloading its index — see 'make logs' or 'docker compose logs -f photon'."

.PHONY: placeholder-data
placeholder-data: ## One-shot: download WOF (~68 GB) + build Placeholder store + auto-cleanup transients
	@if [ -s data/placeholder/store.sqlite3 ]; then \
		echo "Placeholder store already exists at data/placeholder/store.sqlite3 ($$(du -sh data/placeholder/store.sqlite3 | cut -f1))"; \
		echo "  → run 'make placeholder-data-rebuild' to force a fresh build"; \
	else \
		echo "⚠️  pelias/whosonfirst:latest always downloads the global WOF bundle (~68 GB transient)."; \
		echo "⚠️  Allocate ≥16 GB RAM in Docker Desktop or the final optimize step will OOM-kill."; \
		echo "⚠️  Final store.sqlite3 will be ~3-6 GB after build; transients are auto-removed."; \
		mkdir -p data/whosonfirst/sqlite data/placeholder && \
		chmod -R a+rwX data/whosonfirst data/placeholder && \
		UID=$$(id -u) GID=$$(id -g) $(DC) --profile data-setup run --rm whosonfirst && \
		$(DC) run --rm placeholder bash -c "./cmd/extract.sh && ./cmd/build.sh" || true; \
		if [ -s data/placeholder/store.sqlite3 ]; then \
			store_size=$$(du -sh data/placeholder/store.sqlite3 | cut -f1); \
			echo "Placeholder store built: $$store_size — auto-cleaning transients..."; \
			rm -rf data/whosonfirst/* data/placeholder/wof.extract; \
			touch data/whosonfirst/.gitkeep; \
			echo "Cleanup done. data/placeholder = $$(du -sh data/placeholder | cut -f1)"; \
		else \
			echo "ERROR: data/placeholder/store.sqlite3 was not produced. Check 'docker compose logs'."; \
			exit 1; \
		fi; \
	fi

.PHONY: placeholder-data-rebuild
placeholder-data-rebuild: ## Force-rebuild Placeholder store (re-downloads WOF if missing)
	rm -f data/placeholder/store.sqlite3 data/placeholder/wof.extract
	@$(MAKE) placeholder-data

.PHONY: routing
routing: env ## Boot Valhalla (downloads PBF + SRTM tiles on first start)
	$(DC) --profile routing up -d valhalla
	@echo "Valhalla is building tiles — see 'docker compose logs -f valhalla'."

.PHONY: pois
pois: env ## Boot Overpass (long PBF ingest — hours for Germany)
	$(DC) --profile pois up -d overpass
	@echo "Overpass is ingesting the PBF — see 'docker compose logs -f overpass'."

.PHONY: transit
transit: env ## Boot OpenTripPlanner (expects GTFS in data/gtfs/, OSM PBF in data/osm/)
	@if [ -z "$$(ls data/gtfs 2>/dev/null | grep -v .gitkeep)" ]; then \
		echo "ERROR: data/gtfs/ has no feeds. Drop a GTFS .zip first (see README → Data bootstrap → OpenTripPlanner)."; \
		exit 1; \
	fi
	$(DC) --profile transit up -d otp

.PHONY: full
full: env ## Boot the full stack EXCEPT transit (needs manual GTFS feed setup)
	@echo "=== 1/3 Placeholder data prep (this can take a minute) ==="
	@$(MAKE) placeholder-data
	@echo "=== 2/3 Boot every map-service profile in parallel ==="
	$(DC) --profile all up -d
	@echo "=== 3/3 Services starting — first-boot ingests run for hours ==="
	@echo
	@$(MAKE) status
	@echo
	@echo "Progress lives in 'docker compose logs -f photon valhalla overpass'."
	@echo "Map is live at $(APP_URL) immediately; search/route/POIs return graceful 'upstream:unavailable' until each upstream signals ready."

.PHONY: pull
pull: ## Pull the latest CI-built app image from GHCR
	$(DC) pull app

.PHONY: tiles-download
tiles-download: ## Fetch a PMTiles basemap. Defaults to TILES_URL from .env. Use URL=... to override.
	@mkdir -p data/tiles
	@source_url="$(URL)"; \
	if [ -z "$$source_url" ]; then source_url=$$(grep '^TILES_URL=' .env 2>/dev/null | cut -d= -f2-); fi; \
	if [ -z "$$source_url" ]; then \
		echo "No TILES_URL in .env and no URL= provided."; \
		echo "Examples:"; \
		echo "  make tiles-download URL=https://build.protomaps.com/\$$(date -u +%Y%m%d).pmtiles"; \
		echo "  make tiles-download URL=https://download.mapterhorn.com/planet.pmtiles    # stable mirror, ~700 GB"; \
		echo "  make tiles-protomaps-latest                                                # auto-pick today's Protomaps build"; \
		exit 1; \
	fi; \
	target=data/tiles/basemap.pmtiles; \
	echo "→ $$source_url"; \
	echo "→ $$target"; \
	curl -fL --progress-bar -o "$$target.partial" "$$source_url" && mv "$$target.partial" "$$target"; \
	echo "Done: $$(du -sh $$target | cut -f1)"

.PHONY: tiles-protomaps-latest
tiles-protomaps-latest: ## Fetch today's Protomaps planet PMTiles (~100 GB) — works only for builds <30 days old
	@latest=$$(date -u +%Y%m%d); \
	url="https://build.protomaps.com/$$latest.pmtiles"; \
	$(MAKE) tiles-download URL=$$url

.PHONY: tiles-local
tiles-local: ## Switch app to serve the local PMTiles file at /tiles/basemap.pmtiles
	@grep -q '^TILES_URL=' .env && sed -i.bak '/^TILES_URL=/d' .env && rm -f .env.bak; \
	echo "TILES_URL=/tiles/basemap.pmtiles" >> .env; \
	echo "TILES_URL now points to /tiles/basemap.pmtiles (served by Caddy from data/tiles/)"

# ─── Disk / cleanup ───────────────────────────────────────────────────────

.PHONY: disk
disk: ## Show disk usage per data/ subdirectory
	@du -sh data/*/ 2>/dev/null | sort -h

.PHONY: clean-photon
clean-photon: ## Wipe Photon index (forces re-download on next start)
	$(DC) --profile geocoding stop photon || true
	rm -rf data/photon/*

.PHONY: clean-valhalla
clean-valhalla: ## Wipe Valhalla tiles + DEM (forces rebuild on next start)
	$(DC) --profile routing stop valhalla || true
	rm -rf data/valhalla/* data/srtm/*

.PHONY: clean-overpass
clean-overpass: ## Wipe Overpass index (forces re-ingest on next start — hours!)
	$(DC) --profile pois stop overpass || true
	rm -rf data/overpass/*

.PHONY: clean-placeholder
clean-placeholder: ## Wipe Placeholder + WOF (rebuild via 'make placeholder-data')
	$(DC) --profile geocoding stop placeholder || true
	rm -rf data/placeholder/* data/whosonfirst/*

# ─── Smoke tests ──────────────────────────────────────────────────────────

.PHONY: smoke
smoke: ## Curl the public endpoints (expects 'make up' beforehand)
	@echo "→ home"      && curl -fsS -o /dev/null -w "  %{http_code} %{size_download}b\n" $(APP_URL)/
	@echo "→ /up"        && curl -fsS -o /dev/null -w "  %{http_code}\n" $(APP_URL)/up
	@echo "→ /api-docs"  && curl -fsS -o /dev/null -w "  %{http_code} %{size_download}b\n" $(APP_URL)/api-docs/index.html
	@echo "→ search"    && curl -fsS  "$(APP_URL)/api/v1/search?q=berlin"  | head -c 200 && echo
	@echo "→ reverse"   && curl -fsS  "$(APP_URL)/api/v1/reverse?lat=52.5163&lon=13.3777" | head -c 200 && echo
	@echo "→ geocode"   && curl -fsS  "$(APP_URL)/api/v1/geocode?q=munich" | head -c 200 && echo

.PHONY: shell-app
shell-app: ## Open a shell inside the running app container
	$(DC) exec app bash

.PHONY: rails-console
rails-console: ## Rails console inside the app container
	$(DC) exec app bin/rails console
