#!/usr/bin/env python3
"""
Fetch Google Fonts (Outfit / DM Sans / JetBrains Mono) and self-host them.

Atlas is local-first / zero-outbound at runtime. Pulling from
fonts.googleapis.com violates that contract. This script downloads the
woff2 files into priv/static/fonts/ and regenerates assets/css/fonts.css
with @font-face declarations pointing at the local /fonts/ path.

Re-run when adding new families/weights or when Google publishes newer
font versions. The output is fully self-contained — no Google calls at
runtime, ever.

Usage (from app-phoenix/):
    python3 scripts/fetch-fonts.py

Then commit priv/static/fonts/*.woff2 and assets/css/fonts.css.
"""

import os
import re
import sys
import urllib.request

# Edit this list to add/remove families.
FAMILIES = [
    ("Outfit",          [400, 500, 600, 700, 800]),
    ("DM Sans",         [400, 500, 600, 700]),
    ("JetBrains Mono",  [400, 500, 600]),
]
SUBSETS = ("latin", "latin-ext")
UA = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
    "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
)

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FONTS_DIR = os.path.join(ROOT, "priv", "static", "fonts")
CSS_PATH = os.path.join(ROOT, "assets", "css", "fonts.css")


def build_googleapis_url() -> str:
    parts = []
    for fam, weights in FAMILIES:
        wlist = ";".join(str(w) for w in weights)
        parts.append(f"family={fam.replace(' ', '+')}:wght@{wlist}")
    return (
        "https://fonts.googleapis.com/css2?"
        + "&".join(parts)
        + "&display=swap"
    )


def fetch_css(url: str) -> str:
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req) as resp:
        return resp.read().decode("utf-8")


def main() -> int:
    os.makedirs(FONTS_DIR, exist_ok=True)
    css = fetch_css(build_googleapis_url())

    pattern = re.compile(
        r"/\*\s*(\w+(?:-\w+)?)\s*\*/\s*@font-face\s*\{([^}]+)\}",
        re.S,
    )

    out_lines = [
        "/* Self-hosted woff2 fonts. Generated by scripts/fetch-fonts.py from googleapis. */",
        "/* No outbound requests at runtime; vendored in priv/static/fonts/. */",
        "",
    ]
    downloaded = 0

    for match in pattern.finditer(css):
        subset = match.group(1)
        if subset not in SUBSETS:
            continue
        body = match.group(2)
        fam = re.search(r"font-family:\s*'([^']+)'", body).group(1)
        weight = re.search(r"font-weight:\s*(\d+)", body).group(1)
        url = re.search(r"url\((https://[^)]+)\)", body).group(1)
        urange = re.search(r"unicode-range:\s*([^;]+);", body)
        urange = urange.group(1).strip() if urange else None

        slug = fam.lower().replace(" ", "-")
        fname = f"{slug}-{weight}-{subset}.woff2"
        fpath = os.path.join(FONTS_DIR, fname)

        if not os.path.exists(fpath):
            req = urllib.request.Request(url, headers={"User-Agent": UA})
            with urllib.request.urlopen(req) as resp, open(fpath, "wb") as out:
                out.write(resp.read())
            downloaded += 1

        out_lines += [
            "@font-face {",
            f"  font-family: '{fam}';",
            "  font-style: normal;",
            f"  font-weight: {weight};",
            "  font-display: swap;",
            f"  src: url('/fonts/{fname}') format('woff2');",
        ]
        if urange:
            out_lines.append(f"  unicode-range: {urange};")
        out_lines.append("}")

    with open(CSS_PATH, "w") as f:
        f.write("\n".join(out_lines) + "\n")

    total = sum(
        os.path.getsize(os.path.join(FONTS_DIR, n))
        for n in os.listdir(FONTS_DIR)
        if n.endswith(".woff2")
    )
    print(f"Downloaded {downloaded} new files; {total / 1024:.0f} KB total.")
    print(f"Wrote {CSS_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
