#!/usr/bin/env python3
"""Regenerate priv/country_zones.exs from the host's IANA tz database.

    python3 priv/scripts/gen_country_zones.py > priv/country_zones.exs

A country is emitted only when every IANA zone assigned to it keeps the same
UTC offset all year; the zone kept is the one zone.tab lists first, which is
that country's primary zone. The signature is the offset timeline itself, so
two countries that keep the same clock compare equal.
"""

import collections
import datetime
import sys
from zoneinfo import ZoneInfo

ZONE_TAB = "/usr/share/zoneinfo/zone.tab"
YEAR = 2026
STEP_DAYS = 3


def offsets_by_country():
    rows = collections.OrderedDict()
    with open(ZONE_TAB) as fh:
        for line in fh:
            if line.startswith("#") or not line.strip():
                continue
            fields = line.split("\t")
            rows.setdefault(fields[0].lower(), []).append(fields[2].strip())
    return rows


def fmt(delta):
    total = int(delta.total_seconds())
    sign = "+" if total >= 0 else "-"
    total = abs(total)
    return "%s%02d:%02d" % (sign, total // 3600, (total % 3600) // 60)


def signature(zone, samples):
    tz = ZoneInfo(zone)
    points, previous = [], None
    for index, moment in enumerate(samples):
        offset = fmt(moment.replace(tzinfo=tz).utcoffset())
        if offset != previous:
            points.append("%s@%d" % (offset, index))
            previous = offset
    return ",".join(points)


def main():
    base = datetime.datetime(YEAR, 1, 1)
    samples = [base + datetime.timedelta(days=STEP_DAYS * i) for i in range(365 // STEP_DAYS + 1)]

    resolved = {}
    for code, zones in offsets_by_country().items():
        signatures = {signature(zone, samples) for zone in zones}
        if len(signatures) == 1:
            resolved[code] = (zones[0], signatures.pop())

    out = sys.stdout
    out.write("# Generated by priv/scripts/gen_country_zones.py — do not edit by hand.\n")
    out.write("# ISO 3166-1 alpha-2 => {primary IANA zone, %d-sampled UTC-offset timeline}\n" % len(samples))
    out.write("# Source: %s, sampled every %d days across %d.\n" % (ZONE_TAB, STEP_DAYS, YEAR))
    out.write("%{\n")
    for code in sorted(resolved):
        zone, sig = resolved[code]
        out.write('  "%s" => {"%s", "%s"},\n' % (code, zone, sig))
    out.write("}\n")


if __name__ == "__main__":
    main()
